version: '3.7'

services:

  api:
    image: api
    env_file:
      - .env
    container_name: another_tracker_api
    build: ./API
    ports:
      - 80:80

  db:
    image: postgres:16-bullseye
    env_file:
      - .env
    ports:
      - "5430:5432"
    expose:
      - 5430
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  nginx:
    build: .
    container_name: another_tracker_nginx
    ports:
      - "8888:8888"
    depends_on:
      - api
  