version: '3.7'

services:

  api:
    image: api
    env_file:
      - ./prod.env
    container_name: another_tracker_api
    build: ./API
    ports:
      - 80:80

  db:
    image: postgres:16
    env_file:
      - ./prod.env
    ports:
      - "5430:5432"
    expose:
      - 5430
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  nginx:
    build: 
      context: .
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    container_name: another_tracker_nginx
    env_file:
      - ./prod.env
    ports:
      - "8888:8888"
    depends_on:
      - api
  