DROP TABLE IF EXISTS public."users";

CREATE TABLE public."users" 
(
	id SERIAL PRIMARY KEY,
	email TEXT NOT NULL UNIQUE,
	password_hash BYTEA NOT NULL,
	password_salt BYTEA NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);